### PR TITLE
Loosening Octokit version constraint so it doesn't conflict with 4.0.1 of Berkshelf

### PR DESCRIPTION
**Pull request by tyler-ball**
\cc @jkeiser @reset

### CODE REVIEW

**Comment by jkeiser** [comment]
:+1:

**Comment by tyler-ball** [comment]
We should probably add `spec.required_ruby_version = ">= 2.0.0"` to this gemspec since varia_model 0.5 depends on that anyways - @reset ?

**Comment by tyler-ball** [comment]
Passed in a local ChefDK omnibus build and passed `chef verify`

**Comment by tyler-ball** [comment]
Thanks @reset !

**Pull request merged**
