### PR TITLE
Fix incorrect fetching cookbok's metadata

### PR DESCRIPTION
**Pull request by gueux**
Fixed fetching issue when cookbook's repository name
is not equal to cookbook's name in metadata

### CODE REVIEW

**Comment by reset** [comment]
@gueux thanks for the PR! I'd be more than willing to merge this new feature in if you could provide some tests and add to the documentation describing this new configurable option.

**Comment by scalp42** [comment]
@gueux any chance to add doc or tests?

**Comment by gueux** [comment]
Hi, please tell me if this 078034e57769393b19dce655719b077c47135534 rspec test is enought. thanks

**Comment by reset** [comment]
@gueux looks good to me

**Pull request merged**
